---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-template
  namespace: default
spec:
  interval: 30s
  ref:
    branch: fresh
  url: https://github.com/kubasobon/flux-template

