apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ginger-gitops
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-master
  interval: 1m
  path: ./management-clusters/ginger
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: flux-template
  timeout: 2m
